### ISSUE TITLE
JSONDecodeError when running (cli + library)

### ISSUE THREAD

**Issue by mekarpeles** [titusz/epubcheck#5]
```$ epubcheck
Traceback (most recent call last):
  File "/usr/local/bin/epubcheck", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/epubcheck/cli.py", line 88, in main
    for result in results:
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 695, in next
    raise value
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.5/dist-packages/epubcheck/checker.py", line 41, in __init__
    self.run()
  File "/usr/local/lib/python3.5/dist-packages/epubcheck/checker.py", line 58, in run
    self.result_data = json.loads(self._stdout.decode())
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by mekarpeles** [comment]
Looks like the error in this case is related to the `epubcheck.jar` directly:
```
$ java -Duser.language=en -jar epubcheck.jar test.epub -q --profile default --json
Error occurred during initialization of VM
Could not allocate metaspace: 1073741824 bytes
```

**Comment by mekarpeles** [comment]
Adding `-XX:MaxHeapSize=512m -XX:InitialHeapSize=512m -XX:CompressedClassSpaceSize=64m -XX:MaxMetaspaceSize=128m` to the call does the trick...
